# primary author: anuhyag
class SessionsController < ApplicationController

	def create
		new_user_params = {
			fullname: auth_hash.info.name,
			username: auth_hash.info.nickname,
			email: auth_hash.info.email,
			auth_token: auth_hash.credentials.token,
			image_url: auth_hash.extra.raw_info.avatar_url
		}
	    user = User.find_by_uid_or_create(auth_hash.uid, new_user_params)
	    sign_in user
	    render_auth_hash
	    # redirect_back_or user
	end

	def destroy
		sign_out
    	redirect_to root_url
	end

	def oauth_failure
	    sign_out
	    flash[:error] = "You must log into GitHub to continue"
	    redirect_to root_url
	end

	private

    # Get the authorization request object, generated by Omniauth
    # Example auth_hash can be seen here: http://hastebin.com/wobadenoga.sm
    def auth_hash
      request.env['omniauth.auth']
    end

    # Debugging method that displays the full contents of the auth_hash formatted very nicely
    def render_auth_hash
    	render_as_yaml auth_hash
    end
end
