class SessionsController < ApplicationController

	def create
	    user = User.find_by_uid_or_create(auth_hash.uid, auth_hash.info.nickname, auth_hash.info.email, auth_hash.info.name)
	    # render :text => auth_hash.to_yaml, :content_type => 'text/yaml'
	    sign_in user
	    redirect_back_or user
	end

	def destroy
		sign_out
    	redirect_to root_url
	end

	def oauth_failure
	    sign_out
	    flash[:error] = "You must log into GitHub to continue"
	    redirect_to root_url
	end

	private

    # Get the authorization request object, generated by Omniauth
    def auth_hash
      request.env['omniauth.auth']
    end
end
